/** @type {import('tailwindcss').Config} */

/**
 * Theme 1 — Prism Heritage
 * Manage colors, spacing, typography, radius, gradients & motion here.
 */
const tg = {
  colors: {
    bg: '#ffffff',
    soft: '#f5f7fa',
    navy: '#0b1f3a',
    deep: '#061428',
    ink: '#1a2332',
    muted: '#5b6575',
    line: 'rgba(11, 31, 58, 0.1)',
    emerald: '#1fa463',
    cyan: '#1ba3c9',
    amber: '#f0a020',
    coral: '#e85d3b',
  },
  spacing: {
    'hero-top': '1.125rem',
    'hero-top-md': '1.375rem',
    'hero-scroll': '3.5rem',
    'hero-stack': '0.75rem',
    'hero-stack-lg': '1.25rem',
    'hero-stack-xl': '1.5rem',
    'hero-badge-mb': '1.125rem',
    'hero-eyebrow-mb': '0.625rem',
    'hero-title-mb': '0.75rem',
    'hero-line-mb': '1rem',
    'hero-body-mb': '0.875rem',
    'hero-body-mb-lg': '1rem',
    'hero-cta-gap': '1rem',
    'hero-badge-x': '0.75rem',
    'hero-badge-y': '0.4375rem',
    'hero-prism-w': '4rem',
    'btn-x': '1.5rem',
    'btn-y': '0.5625rem',
    'btn-min-h': '2.5rem',
    'btn-nav-x': '1rem',
    'btn-nav-y': '0.5rem',
    'btn-nav-min-h': '2.25rem',
    'topbar-y': '0.375rem',
    'nav-y': '0.5rem',
    'nav-y-md': '0.5625rem',
    'venture-gap': '0.375rem',
    'venture-pad-y': '0.5rem',
    'venture-pad-x': '0.875rem',
    'venture-glass-pad': '0.75rem',
    'sector-gap': '0.5rem',
    'gutter': '1.5rem',
    'section-y': '6rem',
    'scroll-top': '1.5rem',
    'scroll-top-size': '2.75rem',
  },
  borderRadius: {
    tgSm: '0.625rem',
    tgMd: '0.875rem',
    tgLg: '1.25rem',
    tgXl: '1.5rem',
    tgPill: '9999px',
  },
  fontSize: {
    heroDisplay: ['clamp(2rem, 5vw, 4rem)', { lineHeight: '1.08', letterSpacing: '-0.02em', fontWeight: '500' }],
    heroEyebrow: ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.18em', fontWeight: '600' }],
    heroLabel: ['0.6875rem', { lineHeight: '1.2', letterSpacing: '0.16em', fontWeight: '600' }],
    heroBody: ['0.9375rem', { lineHeight: '1.7', fontWeight: '400' }],
    heroBodyLg: ['1.0625rem', { lineHeight: '1.7', fontWeight: '400' }],
    btnMd: ['0.9375rem', { lineHeight: '1.2', fontWeight: '600' }],
    btnSm: ['0.8125rem', { lineHeight: '1.2', fontWeight: '600' }],
    btnNav: ['0.6875rem', { lineHeight: '1.2', letterSpacing: '0.06em', fontWeight: '600' }],
    scrollLabel: ['0.75rem', { lineHeight: '1', letterSpacing: '0.22em', fontWeight: '600' }],
    ventureChip: ['0.8125rem', { lineHeight: '1.3', fontWeight: '500' }],
    topbar: ['0.75rem', { lineHeight: '1', fontWeight: '400' }],
  },
  maxWidth: {
    container: '75rem',
    heroCopy: '32rem',
    heroBody: '28rem',
    venturePanel: '15rem',
  },
  transitionDuration: {
    tg: '300ms',
    tgSlow: '500ms',
  },
  transitionTimingFunction: {
    tg: 'cubic-bezier(0.22, 1, 0.36, 1)',
  },
};

const prismGradient =
  'linear-gradient(90deg, #1fa463, #1ba3c9, #f0a020, #e85d3b)';

function tgThemePlugin({ addBase, theme }) {
  addBase({
    ':root': {
      '--tg-bg': tg.colors.bg,
      '--tg-bg-soft': tg.colors.soft,
      '--tg-navy': tg.colors.navy,
      '--tg-navy-deep': tg.colors.deep,
      '--tg-ink': tg.colors.ink,
      '--tg-muted': tg.colors.muted,
      '--tg-line': tg.colors.line,
      '--tg-prism-emerald': tg.colors.emerald,
      '--tg-prism-cyan': tg.colors.cyan,
      '--tg-prism-amber': tg.colors.amber,
      '--tg-prism-coral': tg.colors.coral,
      '--tg-radius-sm': tg.borderRadius.tgSm,
      '--tg-radius-md': tg.borderRadius.tgMd,
      '--tg-radius-lg': tg.borderRadius.tgLg,
      '--tg-gap-sector': tg.spacing['sector-gap'],
      '--tg-pad-topbar-y': tg.spacing['topbar-y'],
      '--tg-pad-nav-y': tg.spacing['nav-y'],
      '--tg-pad-nav-y-md': tg.spacing['nav-y-md'],
      '--tg-hero-top-gap': tg.spacing['hero-top'],
      '--tg-hero-top-gap-md': tg.spacing['hero-top-md'],
      '--tg-hero-scroll-h': tg.spacing['hero-scroll'],
      '--tg-hero-badge-mb': tg.spacing['hero-badge-mb'],
      '--tg-hero-eyebrow-mb': tg.spacing['hero-eyebrow-mb'],
      '--tg-hero-title-mb': tg.spacing['hero-title-mb'],
      '--tg-hero-line-mb': tg.spacing['hero-line-mb'],
      '--tg-hero-body-mb': tg.spacing['hero-body-mb'],
      '--tg-hero-body-mb-lg': tg.spacing['hero-body-mb-lg'],
      '--tg-hero-badge-x': tg.spacing['hero-badge-x'],
      '--tg-hero-badge-y': tg.spacing['hero-badge-y'],
      '--tg-hero-prism-w': tg.spacing['hero-prism-w'],
      '--tg-btn-x': tg.spacing['btn-x'],
      '--tg-btn-y': tg.spacing['btn-y'],
      '--tg-btn-min-h': tg.spacing['btn-min-h'],
      '--tg-btn-font': tg.fontSize.btnMd[0],
      '--tg-btn-nav-x': tg.spacing['btn-nav-x'],
      '--tg-btn-nav-y': tg.spacing['btn-nav-y'],
      '--tg-btn-nav-min-h': tg.spacing['btn-nav-min-h'],
      '--tg-btn-nav-font': tg.fontSize.btnNav[0],
      '--tg-venture-gap': tg.spacing['venture-gap'],
      '--tg-venture-pad-y': tg.spacing['venture-pad-y'],
      '--tg-venture-pad-x': tg.spacing['venture-pad-x'],
      '--tg-venture-glass-pad': tg.spacing['venture-glass-pad'],
      '--tg-font-scroll-label': tg.fontSize.scrollLabel[0],
      '--tg-font-scroll-icon': '1.75rem',
      '--tg-scroll-top-offset': tg.spacing['scroll-top'],
      '--tg-scroll-top-size': tg.spacing['scroll-top-size'],
      '--tg-prism-gradient': prismGradient,
    },
  });
}

module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    screens: {
      xs: '375px',
      sm: '480px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1440px',
    },
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: tg.borderRadius.tgXl,
        '2xl': '2rem',
        full: '9999px',
        'tg-sm': tg.borderRadius.tgSm,
        'tg-md': tg.borderRadius.tgMd,
        'tg-lg': tg.borderRadius.tgLg,
        'tg-pill': tg.borderRadius.tgPill,
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        tg: {
          bg: 'var(--tg-bg)',
          soft: 'var(--tg-bg-soft)',
          navy: 'var(--tg-navy)',
          deep: 'var(--tg-navy-deep)',
          ink: 'var(--tg-ink)',
          muted: 'var(--tg-muted)',
          line: 'var(--tg-line)',
          emerald: 'var(--tg-prism-emerald)',
          cyan: 'var(--tg-prism-cyan)',
          amber: 'var(--tg-prism-amber)',
          coral: 'var(--tg-prism-coral)',
        },
      },
      spacing: {
        gutter: tg.spacing.gutter,
        'container-max': tg.maxWidth.container,
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'section-gap': tg.spacing['section-y'],
        'hero-top': tg.spacing['hero-top'],
        'hero-top-md': tg.spacing['hero-top-md'],
        'hero-scroll': tg.spacing['hero-scroll'],
        'hero-stack': tg.spacing['hero-stack'],
        'hero-stack-lg': tg.spacing['hero-stack-lg'],
        'hero-stack-xl': tg.spacing['hero-stack-xl'],
        'hero-badge-mb': tg.spacing['hero-badge-mb'],
        'hero-eyebrow-mb': tg.spacing['hero-eyebrow-mb'],
        'hero-title-mb': tg.spacing['hero-title-mb'],
        'hero-line-mb': tg.spacing['hero-line-mb'],
        'hero-body-mb': tg.spacing['hero-body-mb'],
        'hero-body-mb-lg': tg.spacing['hero-body-mb-lg'],
        'hero-cta-gap': tg.spacing['hero-cta-gap'],
        'hero-badge-x': tg.spacing['hero-badge-x'],
        'hero-badge-y': tg.spacing['hero-badge-y'],
        'hero-prism-w': tg.spacing['hero-prism-w'],
        'topbar-y': tg.spacing['topbar-y'],
        'nav-y': tg.spacing['nav-y'],
        'nav-y-md': tg.spacing['nav-y-md'],
        'venture-gap': tg.spacing['venture-gap'],
        'btn-x': tg.spacing['btn-x'],
        'btn-y': tg.spacing['btn-y'],
        'btn-min-h': tg.spacing['btn-min-h'],
        'btn-nav-x': tg.spacing['btn-nav-x'],
        'btn-nav-y': tg.spacing['btn-nav-y'],
        'btn-nav-min-h': tg.spacing['btn-nav-min-h'],
        'scroll-top': tg.spacing['scroll-top'],
        'scroll-top-size': tg.spacing['scroll-top-size'],
      },
      maxWidth: {
        'container-max': tg.maxWidth.container,
        'hero-copy': tg.maxWidth.heroCopy,
        'hero-body': tg.maxWidth.heroBody,
        'venture-panel': tg.maxWidth.venturePanel,
      },
      fontFamily: {
        display: ['Fraunces', 'Georgia', 'serif'],
        sans: ['Outfit', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': [
          'clamp(1.875rem, 4vw, 3.5rem)',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '500' },
        ],
        'headline-xl': [
          'clamp(1.625rem, 3.2vw, 2.75rem)',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '560' },
        ],
        'headline-lg': [
          'clamp(1.25rem, 2.2vw, 1.75rem)',
          { lineHeight: '1.3', fontWeight: '560' },
        ],
        'body-lg': ['1.0625rem', { lineHeight: '1.7', fontWeight: '400' }],
        'body-md': ['0.9375rem', { lineHeight: '1.7', fontWeight: '400' }],
        'label-md': [
          '0.75rem',
          { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '600' },
        ],
        'hero-display': tg.fontSize.heroDisplay,
        'hero-eyebrow': tg.fontSize.heroEyebrow,
        'hero-label': tg.fontSize.heroLabel,
        'hero-body': tg.fontSize.heroBody,
        'hero-body-lg': tg.fontSize.heroBodyLg,
        'btn-md': tg.fontSize.btnMd,
        'btn-sm': tg.fontSize.btnSm,
        'btn-nav': tg.fontSize.btnNav,
        'scroll-label': tg.fontSize.scrollLabel,
        'venture-chip': tg.fontSize.ventureChip,
        topbar: tg.fontSize.topbar,
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'ken-burns': {
          '0%': { transform: 'scale(1)' },
          '100%': { transform: 'scale(1.08)' },
        },
        'scroll-cue': {
          '0%, 100%': { transform: 'translateY(0)', opacity: '1' },
          '50%': { transform: 'translateY(0.4375rem)', opacity: '1' },
        },
        'prism-shift': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-18px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '120% 0' },
          '100%': { backgroundPosition: '-40% 0' },
        },
        'hero-sweep': {
          '0%': { backgroundPosition: '120% 0' },
          '100%': { backgroundPosition: '-30% 0' },
        },
        'hero-dust': {
          '0%': { transform: 'translate3d(0, 0, 0)', opacity: '0.45' },
          '50%': { transform: 'translate3d(-1.5%, -1%, 0)', opacity: '0.65' },
          '100%': { transform: 'translate3d(0.5%, 0.5%, 0)', opacity: '0.45' },
        },
        'live-ping': {
          '0%': { transform: 'scale(1)', opacity: '0.65' },
          '75%, 100%': { transform: 'scale(2.4)', opacity: '0' },
        },
        'live-glow': {
          '0%, 100%': { boxShadow: '0 0 0 2px rgba(255,255,255,0.2), 0 0 8px rgba(31,164,99,0.7)' },
          '50%': { boxShadow: '0 0 0 2px rgba(255,255,255,0.28), 0 0 14px rgba(31,164,99,1)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'ken-burns': 'ken-burns 22s ease-in-out infinite alternate',
        'scroll-cue': 'scroll-cue 1.8s ease-in-out infinite',
        'prism-shift': 'prism-shift 8s ease infinite',
        float: 'float 10s ease-in-out infinite',
        shimmer: 'shimmer 2.8s ease-in-out infinite',
        'hero-sweep': 'hero-sweep 9s ease-in-out infinite',
        'hero-dust': 'hero-dust 22s linear infinite',
        'live-ping': 'live-ping 1.6s cubic-bezier(0, 0, 0.2, 1) infinite',
        'live-glow': 'live-glow 2s ease-in-out infinite',
      },
      backgroundImage: {
        'prism-band': prismGradient,
        'prism-hero-fade': 'linear-gradient(to top, rgba(6, 20, 40, 0.82) 0%, rgba(6, 20, 40, 0.35) 55%, transparent 100%)',
        'tg-scanline':
          'linear-gradient(180deg, transparent 0%, rgba(255,255,255,0.045) 48%, rgba(255,255,255,0.1) 50%, rgba(255,255,255,0.045) 52%, transparent 100%)',
      },
      transitionTimingFunction: {
        tg: tg.transitionTimingFunction.tg,
      },
      transitionDuration: {
        tg: tg.transitionDuration.tg,
        'tg-slow': tg.transitionDuration.tgSlow,
      },
    },
  },
  plugins: [require('tailwindcss-animate'), tgThemePlugin],
};
