import type { ThemeConfig } from '@/themes/types';

export const meridianTheme: ThemeConfig = {
  id: 'meridian',
  name: 'Meridian Atelier',
  tagline: 'Dark cinematic editorial with aurora accents',
  className: 'theme-meridian',
  themeColor: '#0A0D12',
  gradient: 'linear-gradient(90deg, #7c3aed, #06b6d4, #d4a853)',
  colors: {
    bg: '#0a0d12',
    soft: '#151b26',
    navy: '#0a0d12',
    deep: '#060810',
    ink: '#e8eaed',
    muted: '#8b95a8',
    line: 'rgba(232, 234, 237, 0.08)',
    emerald: '#06b6d4',
    cyan: '#06b6d4',
    amber: '#d4a853',
    gold: '#d4a853',
    goldLight: '#e8c96a',
    coral: '#7c3aed',
    violet: '#7c3aed',
    champagne: '#d4a853',
  },
  fonts: {
    display: 'Syne, system-ui, sans-serif',
    sans: 'Plus Jakarta Sans, system-ui, sans-serif',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Syne:wght@500;600;700;800&display=swap',
  },
  layout: {
    showTopBar: false,
    venturesStyle: 'bento',
    galleryStyle: 'masonry',
    navigationStyle: 'pill-glass',
    heroStyle: 'cinematic-split',
  },
  spacing: {
    sectionY: 'clamp(3rem, 7vw, 6rem)',
    containerX: 'clamp(0.75rem, 4vw, 2rem)',
    heroContentRatio: '1.1fr',
    heroVisualRatio: '0.9fr',
  },
  sections: {
    ventures: 'bento',
    about: 'timeline',
    gallery: 'masonry',
    testimonials: 'spotlight',
    cta: 'gradient-electric',
  },
  animation: {
    intensity: 'cinematic',
    respectReducedMotion: true,
    lenisSmoothScroll: true,
    heroParallax: true,
    shaderFallbackMobile: true,
  },
  reactBits: {
    navigation: { pillNav: true, staggeredMenu: true, magnet: true, electricBorder: true },
    hero: {
      blurText: true,
      splitText: true,
      gradientText: true,
      scrollReveal: true,
      aurora: true,
      darkVeil: true,
      noise: true,
    },
    sections: {
      ventures: ['MagicBento', 'AnimatedContent'],
      about: ['ScrollReveal', 'ProfileCard'],
      gallery: ['Masonry', 'TiltedCard'],
      testimonials: ['SpotlightCard', 'CardSwap'],
      cta: ['GradientText', 'Magnet', 'ElectricBorder'],
    },
  },
  assets: {
    basePath: '/assets/themes/meridian',
    hero: {
      videoSrc: '/assets/themes/meridian/hero/meridian-hero-loop.webm',
      posterSrc: '/assets/themes/meridian/hero/meridian-hero-poster.webp',
      fallbackImage: '/assets/themes/meridian/hero/meridian-hero-gallery.webp',
    },
    decorativeSvg: '/assets/themes/meridian/icons/aurora-divider.svg',
  },
  status: 'complete',
};
