import type { ThemeColors } from '@/themes/types';

/** Shared spacing / typography tokens — theme colors come from ThemeConfig. */
export const sharedSpacing = {
  'hero-top': '1.5rem',
  'hero-top-md': '2rem',
  'hero-scroll': '3.25rem',
  'hero-copy': '1.125rem',
  'hero-copy-md': '1.375rem',
  'hero-copy-lg': '1.625rem',
  'hero-stack': '1.25rem',
  'hero-stack-lg': '2.25rem',
  'hero-stack-xl': '3rem',
  'hero-badge-mb': '0',
  'hero-eyebrow-mb': '0.75rem',
  'hero-title-mb': '0',
  'hero-title': '0.875rem',
  'hero-line-mb': '0',
  'hero-body-mb': '0',
  'hero-body-mb-lg': '0',
  'hero-cta': '1rem',
  'hero-cta-mt': '0.75rem',
  'hero-cta-bottom': '0.5rem',
  'hero-badge': '0.5rem',
  'hero-badge-x': '0.625rem',
  'hero-badge-y': '0.3125rem',
  'hero-prism-w': '4rem',
  'btn-x': '1.75rem',
  'btn-y': '0.6875rem',
  'btn-min-h': '2.75rem',
  'btn-nav-x': '1rem',
  'btn-nav-y': '0.5rem',
  'btn-nav-min-h': '2.25rem',
  'topbar-y': '0.375rem',
  'nav-y': '0.5rem',
  'nav-y-md': '0.5625rem',
  'venture-gap': '0.5rem',
  'venture-pad-y': '0.5625rem',
  'venture-pad-x': '1rem',
  'venture-glass-pad': '0.875rem',
  'venture-panel-inset': '0.5rem',
  'sector-gap': '0.5rem',
  gutter: '1.5rem',
  'section-y': '7rem',
  'scroll-top': '1.5rem',
  'scroll-top-size': '2.75rem',
  'header-offset': '4.75rem',
  'header-offset-md': '5.25rem',
} as const;

export function themeColorsToCssVars(colors: ThemeColors, gradient: string): Record<string, string> {
  return {
    '--tg-bg': colors.bg,
    '--tg-bg-soft': colors.soft,
    '--tg-navy': colors.navy,
    '--tg-navy-deep': colors.deep,
    '--tg-ink': colors.ink,
    '--tg-muted': colors.muted,
    '--tg-line': colors.line,
    '--tg-prism-emerald': colors.emerald,
    '--tg-prism-cyan': colors.cyan,
    '--tg-prism-amber': colors.amber,
    '--tg-gold': colors.gold,
    '--tg-gold-light': colors.goldLight,
    '--tg-prism-coral': colors.coral,
    '--tg-prism-gradient': gradient,
  };
}
